### ISSUE TITLE
Cannot read the dataset

### ISSUE THREAD

**Issue by hosseinfani** [ContentWise/contentwise-impressions#1]
I receive an exception at line# 48 when trying to run <run_generate_splits.py> and read the dataset. The exception is raised from the apache parquet. I have installed pyarrow-0.17.1. Below is the stacktrace:

  File "contentwise-impressions-master/run_generate_splits.py", line 48, in <module>
    dataset.read_dataset()
  File "contentwise-impressions-master\Utils\decorator.py", line 21, in timed
    result = method(*args, **kwargs)
  File "contentwise-impressions-master\Utils\dataset.py", line 229, in read_dataset
    self._local_interactions_file_path)
  File "contentwise-impressions-master\Utils\dataset.py", line 213, in _read_parquet
    return ddf.read_parquet(path=local_file_path, engine="pyarrow")
  File "C:\Program Files\Anaconda3\lib\site-packages\dask\dataframe\io\parquet.py", line 1154, in read_parquet
    categories=categories, index=index, infer_divisions=infer_divisions)
  File "C:\Program Files\Anaconda3\lib\site-packages\dask\dataframe\io\parquet.py", line 706, in _read_pyarrow
    pf = piece.get_metadata(_open)
TypeError: get_metadata() takes 1 positional argument but 2 were given

**Comment by fernandobperezm** [comment]
Hello! 

Thanks for raising an issue with the dataset and the code we've published.

Could you please provide me the following information?
- **Your OS**
- **Your conda version**: `conda -V`
- **The packages of the Conda environment**: `conda list -n contentwise-impressions`

From the stacktrace, I can see that you're trying to run the code outside the Conda environment. We highly recommend that you run all the code within it. 

We provide instructions to install the Conda environment and the workspace on the [README](https://github.com/ContentWise/contentwise-impressions#installation). The installation procedure has some differences depending on your OS. We provided instructions for Linux, macOS, and Windows.

If you face problems with the installation or want to suggest changes, please open a new issue. We will gladly help you.

**Comment by hosseinfani** [comment]
I've installed the env by the provided instructions and the issue is resolved.
