### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by JingsenZhang** [ContentWise/contentwise-impressions#2]
Hello,
when i used this datase, i had a problem as follows.
The situation  'when a impressions_without_direct_link is presented, a user interacts with a item which not appear in the impressions  ' is what situation??
is it contained in rec_id=-1 in interactions.csv?

Hope your reply, thank you very much!

**Comment by fernandobperezm** [comment]
Hi!

Interactions with `recommendation_id = -1` are those interactions that the dataset has no impressions. If `recommendation_id ≥ 0` then you can find the impression in the `impressions-direct-link` folder file using that identifier.

Impressions without direct link are those recommendation rows which were presented to the user but did not receive any interaction at that moment. For example, if you are presented with 5 rows and you only click on the first, then rows 2-5 are classified as "Impressions without direct link". You can find these in the `impressions-non-direct-link` folder.

I hope this clarifies your doubts!

**Comment by JingsenZhang** [comment]
Thank you very much! I got it!

**Comment by JingsenZhang** [comment]
For the row of "recommendation_id = -1" in the interaction.csv, could I say "for this user-item interaction, the user did not follow the recommendation but conduct an action based on his own mind? "

**Comment by fernandobperezm** [comment]
Hi!

If `recommendation_id = -1` then that means that the user interacted with a row provided by the OTT service, the dataset contains impressions only for those rows that were generated by our system. 

I hope this clarifies your doubts 😄

**Comment by JingsenZhang** [comment]
Thanks so much for your answer.
Actually, I'm very interested in whether there are some user behaviors that are not influenced by the recommender system. I would like to ask when the user making her decisions, which information is shown to her, just the editorial row or  the editorial row + row 1,2,3?

**Comment by JingsenZhang** [comment]
Is the editorial row also a recommendation list?

**Comment by fernandobperezm** [comment]
Hi @JingsenZhang! Sorry for the delay.

In general, the layout of the user consisted of a vertical stack of rows, where each row is a recommendation list, either generated by the service or provided by us. We call the ones generated by the service as editorial rows, if those were personalized or not is beyond our current knowledge. 

For further details, check Figure 1 and Section 3.1 of the paper, there you'll find a more detailed description of what was shown to the user and the meaning of the elements.

Let me know if you have further questions! I'll happily provide an answer.
