### ISSUE TITLE
Inquiry about recommendation id 

### ISSUE THREAD

**Issue by helenlai** [ContentWise/contentwise-impressions#3]
Hi there, 

Thanks for sharing the dataset. I have read through the corresponding paper and got a few questions that I hope could be clarified.

In the impression with direct link dataset, each row is associated with a recommendation id. May I check if this id is the identifier of the recommendation algorithm used to generate the row or is it purely just treated as a key to merge the impression with direct link dataset with the interaction dataset? If the latter is the case, can I ask if there is anyway to distinguish impressions generated by different recommendation algorithms?

Thanks for in advance for your help. :)

Best wishes,
Helen

**Comment by fernandobperezm** [comment]
Hi @helenlai !

Thanks for your comments! I'm glad you're interested in ContentWise Impressions 😃 

With respect to your question, the `recommendation_id` is as you said in the second case, i.e., just a key to merge those impressions (`direct-link`) with the interactions dataset. Unfortunately, there is no way that we can know which recommendation algorithms generated which impressions 😕

I hope this clarifies your doubts, do not hesitate to ask more questions.

Best regards.

**Comment by helenlai** [comment]
> Hi @helenlai !
> 
> Thanks for your comments! I'm glad you're interested in ContentWise Impressions 😃
> 
> With respect to your question, the `recommendation_id` is as you said in the second case, i.e., just a key to merge those impressions (`direct-link`) with the interactions dataset. Unfortunately, there is no way that we can know which recommendation algorithms generated which impressions 😕
> 
> I hope this clarifies your doubts, do not hesitate to ask more questions.
> 
> Best regards.

Many thanks for your reply. This has clarified my questions. :)
