### ISSUE TITLE
Can I get Item content matrix?

### ISSUE THREAD

**Issue by ParkJinHyeock** [ContentWise/contentwise-impressions#4]
Hello, Thanks for your amazing work! 

I'm now checking the baseline you provided, before starting my research. And I found that 'ItemKNNRecommender.py'  utilizes the item content matrix to compute similarity. But the paper and the dataset you published don't contain item information except for series length and type of the episodes. And there are no parts to make the ICM matrix in 'dataset.py'.  My main questions are as follows.

1. Are the results you reported on the paper as an Item KNN based on the user rating matrix? 
2. If not, how can I get the item content matrix you used to report results? 

Once again, I'm really thankful for providing a great dataset!

**Comment by fernandobperezm** [comment]
Hello! 

Thanks for your interest in our work!

The baselines that we trained and reported in the paper are pure collaborative-filtering approaches, i.e., they do not use content-based features or content matrices. 

To answer your questions, the paper reports ItemKNN trained with only the user-rating matrix 😆

**Comment by ParkJinHyeock** [comment]
Thank you!
