### ISSUE TITLE
Could We Use `*-direct-link` Data to Reconstruct the Recommendation Grid?

### ISSUE THREAD

**Issue by AaronHeee** [ContentWise/contentwise-impressions#7]
Hi ContentWise team,

Thanks for this great work! I have a question about reconstructing the grid of recommended items.

Since we have `impressions-*direct-link` datasets that contain row positions of recommended series lists. I wonder if it is possible to reconstruct the grid of recommendation items that user viewed before? 

For example,

1. Find [user1, rec1, row=1] from `impressions-direct-link` dataset (user identifier is retrieved from `interactions`);
2. Find [user1, row={2,3,4,5}] from `impressions-none-direct-link` dataset;
3. Combine them together as a 5-row grid of recommendations where user1 interacted with the first row only.

Looking forward to hearing your suggestions about this idea. Is it possible (since we don't know the timestamps in `impressions-none-direct-link`)?

**Comment by fernandobperezm** [comment]
Hi!

I think it is possible to reconstruct the grid/layout to a limited extent. Sadly, for the `impressions-non-direct-link` dataset it is not possible to reconstruct the grid as it does not have timestamps. It can neither be used alongside the `interactions` or `impressions-direct-link` given that you won't be able to distinguish when in time to place an impression from the former dataset occurred into the others.

Despite this, I think that you can partially reconstruct the grid/layout using the timestamps contained in the `interactions` and `impressions-direct-link` datasets. Particularly, you can create a "screen" by setting a threshold (e.g. 1min) in which all the interactions and impressions that occurred inside the threshold are contained in the same "screen". This is a similar approach to how sessions are created when session information is not available. 

This approach may allow you to recreate the layout if the user interacted with several rows within that threshold, although remember that for certain rows (editorial rows, and others) there are no impressions records and there is no information in the dataset about their layout positioning. Hence, the "screen" that you're creating may not be a 100% representation of what the user saw on-screen.

Hope this answer your questions 😊

**Comment by AaronHeee** [comment]
Thanks for your timely reply! It helps me a lot :D
